#:import colors config.colors.colors

<ItemNavBar>:
    orientation: 'vertical'
    size_hint: None, 1
    Image:
        source: root.icon_selected if root.is_selected else root.icon
        pos_hint: {'center_x': 0.5}
    Label:
        text: root.text
        font_size: '12pt'
        size_hint_x: None
        width: self.texture_size[0]
        pos_hint: {'center_x': 0.5}
        color: colors["selected"] if root.is_selected else colors["font"]

